name = "RobSIRs"
uuid = "7c1f9049-52e7-4a2d-b60c-f82f9109c5f1"
authors = ["Ali R. Vahdati <arv.kavir@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
